force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>An object to enters Car information.</description>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>MUV</fullName>
            </value>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>MSRP</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CarController.cls
public with sharing class CarController {
  @AuraEnabled(Cacheable=true)
  public static List<Car__c> getCars(FiltersWrapper filters) {
    String key, whereClause = '';
    Decimal price;
    String[] categories, makeType, criteria = new List<String>();

    if (filters != null) {
      price = filters.price;
      categories = filters.categories;
      makeType = filters.maketype;

      if (!String.isEmpty(filters.searchKey)) {
        key = '%' + filters.searchKey + '%';
        criteria.add('Name LIKE: key');
      }

      if (filters.price >= 0) {
        criteria.add('MSRP__c <= :price');
      }

      if (filters.categories != null) {
        criteria.add('Category__c IN :categories');
      }

      if (filters.maketype != null) {
        criteria.add('Make__c IN :makeType');
      }

      if (criteria.size() > 0) {
        whereClause = 'WHERE ' + String.join(criteria, ' AND ');
      }
    }

    String query =
      'SELECT Id, Name, Picture_URL__c, Category__c, Make__c, MSRP__c, Fuel_Type__c, Number_of_Seats__c, Control__c FROM Car__c' +
      whereClause +
      ' WITH SECURITY_ENFORCED' +
      ' ORDER BY Name';

    return Database.query(query);
  }

  // wrapper class
  public class FiltersWrapper {
    @AuraEnabled
    public String searchKey { get; set; }
    @AuraEnabled
    public String price { get; set; }
    @AuraEnabled
    public String[] categories { get; set; }
    @AuraEnabled
    public String[] maketype { get; set; }
  }
}